apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop-demo
  
  template:
    metadata:
      labels:
        app: crashloop-demo
    spec:
      containers:
        - name: crashloop-container
          image: busybox:1.36
          command: ["bin/sh", "-c"]
          args: ["echo 'This container will crashloop' && exit 1"]