apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cm-secret-demo
  template:
    metadata:
      labels:
        app: cm-secret-demo
    spec:
      containers:
        - name: demo
          image: busybox
          command: ["bin/sh", "-c"]
          args:
            - |
              echo "===ENV VARIABLES===";
              env | egrep 'LOG_LEVEPL|DB_PASSWORD|API_KEY' || TRUE;
              echo "===CM FILES===";
              cat /etc/config/app.properties || TRUE;
              echo "===SECRET FILES===";
              ls -l /etc/secret || true;
              echo "DB_PASSWORD file:"; cat /etc/secret/DB_PASSWORD || TRUE;
              echo "Sleeping..."; sleep 3600
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: app-cm
                  key: LOG_LEVEL
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: API_KEY
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: cm-vol
              mountPath: /etc/config
              readOnly: true
            - name: secret-vol
              mountPath: /etc/secret
              readOnly: true
      volumes:
        - name: cm-vol
          configMap:
            name: app-cm
        
        - name: secret-vol
          secret:
            secretName: app-secret